// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd-_AWcemJMNaVEtsjPTl5nRC-sWUn2_Y',
    appId: '1:620565585878:android:a1f40417f9513f90870e77',
    messagingSenderId: '620565585878',
    projectId: 'flat-o-mate',
    storageBucket: 'flat-o-mate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8154IXhG3RVYG6QwSpQok39IOeLNLphI',
    appId: '1:620565585878:ios:b9efea21eb21876f870e77',
    messagingSenderId: '620565585878',
    projectId: 'flat-o-mate',
    storageBucket: 'flat-o-mate.appspot.com',
    iosClientId: '620565585878-q2l19517vm81j079im1npp960035aj6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flatomate',
  );
}
